/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.0.M17
 * Generated at: 2017-09-22 02:16:50 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.ArrayList;
import java.util.*;
import com.Jbean.*;

public final class adminPage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("com.Jbean");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<link rel = \"stylesheet\" type = \"text/css\" href = \"/librarySystem/css/adminPage.css\"/>\r\n");
      out.write("<script type = \"text/javascript\" src = \"/librarySystem/jQuery/jQuery-compressed.js\" ></script>\r\n");
      out.write("<script type = \"text/javascript\" src = \"/librarySystem/script/adminPage.js\" ></script>\r\n");
      out.write("<title>管理员</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("               <div class = \"top\">\r\n");
      out.write("                         <ul>\r\n");
      out.write("                                 <li><a href = \"/librarySystem/index.jsp\">首页</a></li>                           \r\n");
      out.write("                                 <li>\r\n");
      out.write("                                      <img src = \"images/shutdown.ico\" width = \"12px\" height = \"12px\"/>\r\n");
      out.write("                                      <form action = \"/librarySystem/AdminDeal\" method = \"post\">\r\n");
      out.write("                                                  <input type = \"submit\" name = \"deal\"  value = \"退出系统\"  required/>\r\n");
      out.write("                                      </form>\r\n");
      out.write("                                 \r\n");
      out.write("                                 </li>                                 \r\n");
      out.write("                         </ul>                           \r\n");
      out.write("               </div>\r\n");
      out.write("               <div class = \"center\">\r\n");
      out.write("                         <div class = \"centerLeft floatLeft\">\r\n");
      out.write("                                    <ul>\r\n");
      out.write("                                          <li>\r\n");
      out.write("                                              <span>图书管理<span></span></span>                                               \r\n");
      out.write("                                               <ul>\r\n");
      out.write("                                                    <li><a>添加图书</a></li>                                                    \r\n");
      out.write("                                                    <li><a>更新图书</a></li>\r\n");
      out.write("                                                    <li><a>删除图书</a></li>\r\n");
      out.write("                                               </ul>\r\n");
      out.write("                                          </li>\r\n");
      out.write("                                          <li>\r\n");
      out.write("                                                <span>书籍列表<span></span></span>                                                       \r\n");
      out.write("                                               <ul>\r\n");
      out.write("                                                    <li><a>文学</a></li>                                                    \r\n");
      out.write("                                                    <li><a>经济</a></li>\r\n");
      out.write("                                                    <li><a>历史</a></li>\r\n");
      out.write("                                                    <li><a>军事</a></li>\r\n");
      out.write("                                                    <li><a>政治</a></li>\r\n");
      out.write("                                                    <li><a>地理</a></li>\r\n");
      out.write("                                                    <li><a>医学</a></li>\r\n");
      out.write("                                               </ul>\r\n");
      out.write("                                          </li>\r\n");
      out.write("                                          <li>\r\n");
      out.write("                                               <span>借阅书籍查看<span></span></span>                                                             \r\n");
      out.write("                                               <ul>\r\n");
      out.write("                                                    <li><a>查看</a></li>                                                    \r\n");
      out.write("                                               </ul>\r\n");
      out.write("                                          </li>\r\n");
      out.write("                                          <li>\r\n");
      out.write("                                               <span>设置管理员<span></span></span>                                         \r\n");
      out.write("                                                <ul>\r\n");
      out.write("                                                     <li></li>\r\n");
      out.write("                                                </ul>\r\n");
      out.write("                                          </li>\r\n");
      out.write("                                          <li>\r\n");
      out.write("                                               <span>管理员信息<span></span></span>                                                         \r\n");
      out.write("                                                <ul>\r\n");
      out.write("                                                     <li><a>个人资料</a></li>\r\n");
      out.write("                                                     <li><a>添加用户</a></li>\r\n");
      out.write("                                                     <li><a>用户查询</a></li>\r\n");
      out.write("                                                </ul>\r\n");
      out.write("                                          </li>\r\n");
      out.write("                                    </ul>                                  \r\n");
      out.write("                         </div>       \r\n");
      out.write("                         <div class = \"centerRight floatRight\">\r\n");
      out.write("                                 <span>welcome</span>\r\n");
      out.write("                                 <form action = \"/librarySystem/BookDeal\" method = \"post\" onsubmit = \"return check1(this);\">\r\n");
      out.write("                                         <table border = 1>\r\n");
      out.write("                                                    <tr>\r\n");
      out.write("                                                             <td>书编号:</td>\r\n");
      out.write("                                                             <td><input type = \"text\" name = \"bookNumber\" maxlength = \"13\" /></td>\r\n");
      out.write("                                                    </tr>\r\n");
      out.write("                                                    <tr>\r\n");
      out.write("                                                             <td>书名:</td>\r\n");
      out.write("                                                             <td><input type = \"text\" name = \"bookName\" id = \"bookName\" maxlength = \"20\" /></td>\r\n");
      out.write("                                                    </tr>\r\n");
      out.write("                                                    <tr>\r\n");
      out.write("                                                             <td>作者:</td>\r\n");
      out.write("                                                             <td><input type = \"text\" name = \"authorName\" id = \"authorName\" maxlength = \"20\" /></td>\r\n");
      out.write("                                                    </tr>\r\n");
      out.write("                                                     <tr>\r\n");
      out.write("                                                             <td>出版社:</td>\r\n");
      out.write("                                                             <td><input type = \"text\" name = \"publishName\" id = \"publishName\" maxlength = \"20\" /></td>\r\n");
      out.write("                                                    </tr>\r\n");
      out.write("                                                    <tr>\r\n");
      out.write("                                                             <td>租价:</td>\r\n");
      out.write("                                                             <td><input type = \"text\" name = \"bookPrice\" id = \"bookPrice\" maxlength = \"3\" /></td>\r\n");
      out.write("                                                    </tr>\r\n");
      out.write("                                                    <tr>\r\n");
      out.write("                                                             <td>数量:</td>\r\n");
      out.write("                                                             <td><input type = \"text\" name = \"bookCount\" id = \"bookCount\" maxlength = \"4\" /></td>\r\n");
      out.write("                                                    </tr>\r\n");
      out.write("                                                    <tr>\r\n");
      out.write("                                                             <td colspan = 2><input type = \"submit\" name = \"deal\" value = \"添加\" /></td>\r\n");
      out.write("                                                    </tr>\r\n");
      out.write("                                        </table>                                 \r\n");
      out.write("                                 </form>\r\n");
      out.write("                                          <table border = 1 class = \"show\">\r\n");
      out.write("                                                       <tr>\r\n");
      out.write("                                                            <th>学号</th>\r\n");
      out.write("                                                            <th>姓名</th>\r\n");
      out.write("                                                            <th>书名</th>\r\n");
      out.write("                                                            <th>借书时间</th>\r\n");
      out.write("                                                            <th>还书时间</th>\r\n");
      out.write("                                                       </tr>\r\n");
      out.write("                                                               ");
                                                                      
                                                                      List<MyBooks> bookList = (ArrayList<MyBooks>)session.getAttribute("userBookList");
                                                                        if(bookList != null){
                                                                        	   for(MyBooks books:bookList){                                                                        		   
                                                                        	        
      out.write("                                  \r\n");
      out.write("                                                                        \t        <tr>                                      \t    \r\n");
      out.write("\t                                                                        \t        <td>");
      out.print( books.getUid() );
      out.write("</td>\r\n");
      out.write("\t                                                                        \t        <td>");
      out.print( books.getUname() );
      out.write("</td>\r\n");
      out.write("\t                                                                        \t        <td>");
      out.print( books.getBname() );
      out.write("</td>\r\n");
      out.write("\t                                                                        \t        <td>");
      out.print( books.getBtime() );
      out.write("</td>\r\n");
      out.write("\t                                                                        \t        <td>");
      out.print( books.getRtime() );
      out.write("</td>\r\n");
      out.write("                                                                        \t        </tr>                                                                        \t        \r\n");
      out.write("                                                                        \t        ");

                                                                        	   }
                                                                        }
                                                               
      out.write("                                                       \r\n");
      out.write("                                          </table>\r\n");
      out.write("                         </div> \r\n");
      out.write("                         <div class = \"clear\"></div>\r\n");
      out.write("                         <span class = \"message\">");
      out.print(session.getAttribute("exist")==null?"":session.getAttribute("exist") );
      out.write("</span> \r\n");
      out.write("                         <span class = \"message\">");
      out.print(session.getAttribute("delete")==null?"":session.getAttribute("delete") );
      out.write("</span>                                                                                                        \r\n");
      out.write("               </div>\r\n");
      out.write("                  \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
