/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.0.M17
 * Generated at: 2017-09-22 02:16:07 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import org.apache.jasper.tagplugins.jstl.core.Url;
import java.net.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.net");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("org.apache.jasper.tagplugins.jstl.core.Url");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>library System</title>\r\n");
      out.write("<link rel = \"shortCut Icon\" href = \"images/Library.ico\"/>\r\n");
      out.write("<link rel = \"stylesheet\" type = \"text/css\" href = \"css/index.css\"/>\r\n");
      out.write("<script type = \"text/javascript\" src = \"jQuery/jQuery-compressed.js\" ></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("                   <div class = \"top\">   \r\n");
      out.write("                               <span><a href = \"\">首页</a></span> \r\n");
      out.write("                               <span>欢迎光临！\r\n");
      out.write("                               <span id = \"userType\" style = \"font-size:15px;color:white;\">");
      out.print( session.getAttribute("username")!= null?session.getAttribute("username"):"游客" );
      out.write("</span>\r\n");
      out.write("                               </span>                                                                                                                 \r\n");
      out.write("                               <ul class = \"floatRight\">\r\n");
      out.write("                                     <li>\r\n");
      out.write("                                          <img src = \"images/search2.png\"/>\r\n");
      out.write("                                          <input type = \"text\" id = \"search\"/>\r\n");
      out.write("                                          <a href = \"\"><input type = \"button\" value = \"搜索\" id = \"searchBtn\"/></a>\r\n");
      out.write("                                     </li> \r\n");
      out.write("                                     <li>                                         \r\n");
      out.write("                                         <input type = \"button\" value = \"登录\" id = \"login\"/>                                                                                      \r\n");
      out.write("                                         <div class = \"loginUI\">                                                      \r\n");
      out.write("                                                     <span class = \"floatRight\"><img id = \"fork\" src = \"images/fork.png\"/></span>\r\n");
      out.write("                                                     <span class = \"floatLeft\">会员登录</span>\r\n");
      out.write("                                                     <span class = \"floatRight\">还没有账号<a href = \"/librarySystem/register.jsp\">立即注册</a></span>                                                                                                         \r\n");
      out.write("                                                       <form action = \"/librarySystem/UserDeal\" method = \"post\" onsubmit = \"return check(this);\" id = \"form1\">                                                      \r\n");
      out.write("                                                         <table border = 1>\r\n");
      out.write("                                                                 <tr>\r\n");
      out.write("                                                                        <td><img src = \"images/idIMG.png\" width = \"60px\" height = \"60px\"/></td>\r\n");
      out.write("                                                                        <td><input type = \"text\" id = \"UID\" name = \"UID\" maxlength=\"8\" placeholder = \"学号\" /></td>\r\n");
      out.write("                                                                 </tr>\r\n");
      out.write("                                                                 <tr>\r\n");
      out.write("                                                                        <td><img src = \"images/key.png\" width = \"60px\" height = \"60px\"/></td>\r\n");
      out.write("                                                                        <td><input type = \"password\" id = \"UPWD\" name = \"UPWD\" maxlength = \"20\"  placeholder = \"密码\" /></td>\r\n");
      out.write("                                                                 </tr>\r\n");
      out.write("                                                                 <tr>                                                                        \r\n");
      out.write("                                                                        <td colspan = 2>                                                                               \r\n");
      out.write("                                                                               <input type = \"submit\" id = \"login2\" value = \"登录\" name = \"deal\"/>   \r\n");
      out.write("                                                                               <span class = \"floatLeft\">\r\n");
      out.write("                                                                                                <input type = \"radio\" name = \"Utype\" id = \"UtypeS\" value = \"student\" checked />学生\r\n");
      out.write("                                                                                                <input type = \"radio\" name = \"Utype\" id = \"UtypeAD\" value = \"administrator\" />管理员\r\n");
      out.write("                                                                               </span>                                                                           \r\n");
      out.write("                                                                               <span><a href = \"/librarySystem/getPWD.jsp\">忘记密码？</a></span>\r\n");
      out.write("                                                                        </td>\r\n");
      out.write("                                                                 </tr>\r\n");
      out.write("                                                         </table> \r\n");
      out.write("                                                    </form>                                                        \r\n");
      out.write("                                                   <div class = \"clear\"></div>\r\n");
      out.write("                                                   <div class = \"clear\"></div>                                                                                                       \r\n");
      out.write("                                              </div>\r\n");
      out.write("                                         <a href = \"/librarySystem/register.jsp\"><input type = \"button\" value = \"注册\" id = \"register\"  required/></a>\r\n");
      out.write("                                     </li>                                     \r\n");
      out.write("                               </ul>      \r\n");
      out.write("                              <div class = \"clear\"></div>                           \r\n");
      out.write("                   </div>\r\n");
      out.write("                   <div class = \"clear\"></div>\r\n");
      out.write("                   <div class = \"commend\">\r\n");
      out.write("                                <div class = \"commendLeft floatLeft\">\r\n");
      out.write("                                           <ul>\r\n");
      out.write("                                                    <li>文学</li>\r\n");
      out.write("                                                    <li>经济</li>\r\n");
      out.write("                                                    <li>历史</li>\r\n");
      out.write("                                                    <li>军事</li>\r\n");
      out.write("                                                    <li>政治</li>\r\n");
      out.write("                                                    <li>地理</li>\r\n");
      out.write("                                                    <li>医学</li>\r\n");
      out.write("                                           </ul>  \r\n");
      out.write("                                 </div>\r\n");
      out.write("                                 <div class = \"commendCenter floatLeft\">\r\n");
      out.write("                                             <ul>\r\n");
      out.write("                                                   <li><a href = \"\"><img src = \"images/books/literature/1.jpg\"/><br><span>《最终》<br>作者：某某<br>租金：￥30/月</span></a></li>\r\n");
      out.write("                                                   <li><a href = \"\"><img src = \"images/books/literature/2.jpg\"/><br><span>《骆驼祥子》<br>作者：老舍<br>租金：￥30/月</span></a></li>\r\n");
      out.write("                                                   <li><a href = \"\"><img src = \"images/books/literature/3.jpg\"/><br><span>《麦田里的守望者》<br>作者:<br>租金：￥30/月</span></a></li>\r\n");
      out.write("                                                   <li><a href = \"\"><img src = \"images/books/literature/4.jpg\"/><br><span>《流年里的花开》<br>作者:<br>租金：￥30/月</span></a></li>\r\n");
      out.write("                                                   <li><a href = \"\"><img src = \"images/books/literature/5.jpg\"/><br><span>《茶馆》<br>作者:老舍<br>租金：￥30/月</span></a></li>\r\n");
      out.write("                                                   <li><a href = \"\"><img src = \"images/books/literature/6.jpg\"/><br><span>《你好青春》<br>作者:<br>租金：￥30/月</span></a></li>\r\n");
      out.write("                                                   <li><a href = \"\"><img src = \"images/books/literature/7.jpg\"/><br><span>《朝花夕拾》<br>作者:<br>租金：￥30/月</span></a></li>\r\n");
      out.write("                                                   <li><a href = \"\"><img src = \"images/books/literature/8.jpg\"/><br><span>《中国古代文学作品选》<br>作者:<br>租金：￥30/月</span></a></li>\r\n");
      out.write("                                                   <li><a href = \"\"><img src = \"images/books/literature/9.jpg\"/><br><span>《中国古典文学》<br>作者:<br>租金：￥30/月</span></a></li>\r\n");
      out.write("                                                   <li><a href = \"\"><img src = \"images/books/literature/10.jpg\"/><br><span>《狂人日记》<br>作者:<br>租金：￥30/月</span></a></li>\r\n");
      out.write("                                             </ul>\r\n");
      out.write("                                              <div class = \"clear\"></div>\t                                             \t\t                               \r\n");
      out.write("                                </div> \r\n");
      out.write("                                 <div class = \"commendRight floatRight\">\r\n");
      out.write("\t\t\t                                  <a href = \"\">更多>>>>></a> \r\n");
      out.write("\t\t\t                     </div>\r\n");
      out.write("                   </div>                 \r\n");
      out.write("                  \r\n");
      out.write("                                  \r\n");
      out.write("</body>\r\n");
      out.write("<script type = \"text/javascript\" src = \"script/index.js\"></script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
